### PR TITLE
Add getCeilingEnd method

### PR DESCRIPTION
**Pull request by morrislaptop**
This PR adds a method to the period class, `getCeilingEnd()` which will round the included end DateTime to the last second of the precision mask.

Useful when using the Period class outside of its context / precision. Getting the end date from the period I would assume to be the last moment within a higher precision.  In my case we have a DAY precision for our period but are persisting into SECOND precision in the database with timezone support etc..

Usage:

```php
$period = Period::make('2018-01-01', '2018-01-15', Precision::DAY);
$period->getIncludedEnd(); // 2018-01-15 00:00:00
$period->getCeilingEnd(); // 2018-01-15 23:59:59
```

```php
$period = Period::make('2018-01-01', '2018-01-15', Precision::DAY, Boundaries::EXCLUDE_END);
$period->getIncludedEnd(); // 2018-01-14 00:00:00
$period->getCeilingEnd(); // 2018-01-14 23:59:59
```

Also small docs fix.

### CODE REVIEW

**Comment by brendt** [comment]
> which will round the included end DateTime to the last second of the precision mask.

I'm not sure I got what you meant, do you want to always get a precision based on seconds?

**Comment by morrislaptop** [comment]
> > which will round the included end DateTime to the last second of the precision mask.
> 
> I'm not sure I got what you meant, do you want to always get a precision based on seconds?

Yes, because that's the DateTime precision.

**Comment by morrislaptop** [comment]
What about?

```php
$period->getIncludedEnd(Precision::SECOND);
$period->getCeilingEnd(Precision::SECOND);
```

The precision passed would have to be higher specificity than the precision set in $period.

**Comment by brendt** [comment]
Oh, I like that one! Could you target it towards the `2.0` branch though? Lots of changes going to happen

**Comment by morrislaptop** [comment]
Moved to https://github.com/spatie/period/pull/81

**Pull request closed without merging**
