### PR TITLE
add renew function

### PR DESCRIPTION
**Pull request by morrislaptop**
This function allows to repeat or renew a period into the next term. Usage:

```
$period = Period::make('2018-01-01', '2018-01-15');
$rewewal = $period->renew();
```

$renewal will now be from '2018-01-16' to '2018-01-31' (15 days)

### CODE REVIEW

**Comment by brendt** [comment]
Nice! Would you mind also adding an entry to the README?

**Comment by morrislaptop** [comment]
@brendt readme updated

**Comment by brendt** [comment]
Thanks!

**Comment by brendt** [comment]
Tagged: https://github.com/spatie/period/releases/tag/1.6.0

**Pull request merged**
