### PR TITLE
Let length() use the Period's precision

### PR DESCRIPTION
**Pull request by jeromegamez**
Replaces #21 (same contents, but more fitting branch name 🤷‍♂️)

:octocat:

### CODE REVIEW

**Comment by brendt** [comment]
Awesome! Let's discuss other new features in #22 !

**Comment by kylekatarnls** [comment]
`iterator_count` proceeds the whole iteration (that can be very long). A faster approches would be to use the diff but get the unit according to the precisionMask.

See the code:

```php
Period::make('2000-01-01', '2100-01-01')->length();
```

Right now it takes 1.50ms. With iterator_count: 22.54ms

**Comment by brendt** [comment]
Are you able to submit a PR for this?

**Comment by kylekatarnls** [comment]
Yep, please assign it to me, so it will be in my todo-filter.

**Comment by brendt** [comment]
Cool, appreciate it!

**Comment by kylekatarnls** [comment]
See #42

**Pull request merged**
